"""Self-describing recovered-island metadata + auto-discovery.

A recovered function carries its own provenance via the :func:`oracle_link`
decorator: which original PRE2 boundary it replaces, the caller-visible contract it
honours, how far it is verified, and the larger subsystem it will merge into. The
decorator returns the function unchanged, so recovered code keeps normal signatures
and reads like ordinary source — this is a documentation/testing aid, never a
runtime dependency or an ASM dispatcher.

The principle: **code is the source of truth.** Metadata lives next to the code;
docs/registries are *discovered and generated* from it (:func:`collect_islands`,
:func:`render_manifest`) rather than hand-maintained, so they cannot drift. Run
``python scripts/gen_island_manifest.py`` to regenerate the manifest; a test checks
it stays in sync.

Lives at the ``pre2`` top level (not under ``codecs``/``recovered``) so every clean
layer can self-describe without an awkward cross-layer import; it has no VM deps.
"""
from __future__ import annotations

import importlib
import pkgutil
from dataclasses import dataclass
from pathlib import Path

#: allowed maturity levels, in increasing confidence
#: GUESS        - hypothesised from a reference/heuristic, not yet checked vs ASM
#: OBSERVED     - behaviour watched in the running ASM, not yet reimplemented
#: RECOVERED    - reimplemented as clean source, not yet diffed vs ASM
#: ASM_MATCHED  - output diffed against ASM on captured cases
#: VERIFIED     - byte-exact vs ASM under in-VM lockstep over real runs
#: CANONICAL    - verified and adopted as the source of truth (ASM retired for it)
STATUSES = ("GUESS", "OBSERVED", "RECOVERED", "ASM_MATCHED", "VERIFIED", "CANONICAL")

#: packages scanned for recovered islands (any function decorated with oracle_link)
_ISLAND_PACKAGES = ("pre2.codecs", "pre2.recovered")


@dataclass(frozen=True)
class OracleLink:
    boundary: str            # original ASM CS:IP replaced, e.g. "1030:348D"
    contract: str            # caller-visible side effects this function reproduces
    status: str = "RECOVERED"
    merge_target: str = ""   # the larger recovered subsystem this island merges into

    def __post_init__(self) -> None:
        if self.status not in STATUSES:
            raise ValueError(f"OracleLink status {self.status!r} not in {STATUSES}")


def oracle_link(boundary: str, contract: str, status: str = "RECOVERED", merge_target: str = ""):
    """Attach an :class:`OracleLink` to a recovered function (returns it unchanged)."""
    link = OracleLink(boundary, contract, status, merge_target)

    def _decorate(fn):
        fn.oracle_link = link
        return fn

    return _decorate


def collect_islands(packages=_ISLAND_PACKAGES):
    """Discover every recovered island by scanning the recovered packages.

    Walks the package modules, imports them, and yields
    ``(module, qualname, OracleLink)`` for each function carrying ``oracle_link``.
    Adding a new island anywhere under these packages needs no manual registration.
    """
    found: list[tuple[str, str, OracleLink]] = []
    for pkg_name in packages:
        pkg = importlib.import_module(pkg_name)
        for info in pkgutil.walk_packages(pkg.__path__, prefix=pkg_name + "."):
            mod = importlib.import_module(info.name)
            for name, obj in vars(mod).items():
                link = getattr(obj, "oracle_link", None)
                # attribute each island to its *defining* module (skip re-exports)
                if (isinstance(link, OracleLink) and callable(obj)
                        and getattr(obj, "__module__", None) == info.name):
                    found.append((info.name, name, link))
    return sorted(found, key=lambda t: (t[2].boundary, t[1]))


def render_manifest(packages=_ISLAND_PACKAGES) -> str:
    """Render the recovered-island manifest (markdown) from the in-code metadata."""
    lines = [
        "# Recovered islands — generated manifest",
        "",
        "<!-- GENERATED by `python scripts/gen_island_manifest.py`; do not edit by hand.",
        "     Source of truth = the @oracle_link metadata on each recovered function.",
        "     tests/test_island_registry.py fails if this file drifts from the code. -->",
        "",
        "Each row is a recovered leaf/controller. See `AGENTS.md` for the north star (hybrid",
        "recovered-source runtime; original = oracle), the **one-leaf-many-adapters** rule, the **status",
        "taxonomy** (1 recovered+live-grounded / 2 recovered+verify-only / 3 faithful-only / 4 gap /",
        "5 blocked-history-dependent-buffer / 6 not-worth-hooking), and the **collapse rule** (collapse",
        "leaves into larger islands ONLY with evidence from the real original call graph). The `Status`",
        "column below is the oracle-link confidence (GUESS→OBSERVED→ASM_MATCHED→VERIFIED→CANONICAL); the",
        "live-grounded vs verify-only vs faithful-only adapter state is tracked in `faithful_visual_layer.md`.",
        "",
        "| ASM boundary | Function | Status | Merge target | Contract |",
        "|---|---|---|---|---|",
    ]
    for modname, name, link in collect_islands(packages):
        short = modname.split(".", 1)[1] if "." in modname else modname
        lines.append(f"| `{link.boundary}` | `{short}.{name}` | {link.status} | "
                     f"{link.merge_target or '—'} | {link.contract} |")
    return "\n".join(lines) + "\n"


MANIFEST_PATH = Path(__file__).resolve().parents[1] / "docs" / "pre2" / "recovered_islands.md"
