"""Generate the bridge's FIELD REGISTRY from the shipped view declarations (the field-backed flip, step 4).

The views (pre2/views/dgroup_view.py) are the single human-readable declaration of the game's named state —
descriptors annotated with ASM evidence. The BRIDGE side (verification, snapshots, named diffs) needs the
same map machine-readable: every named field flattened to ``name -> (offset, width)``. This generator
harvests the descriptors and StructArrays and writes ``pre2/bridge/field_registry.py`` — the offset table
generates INTO the bridge; the workbench never re-derives layout by hand.

Regenerate after any view change:

    python scripts/gen_field_registry.py

A test (tests/test_field_registry.py) regenerates in-memory and fails if the checked-in file drifted.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

OUT = ROOT / "pre2" / "bridge" / "field_registry.py"

HEADER = '''"""MACHINE-GENERATED by scripts/gen_field_registry.py -- do NOT edit; regenerate after view changes.

The flattened name -> (DGROUP offset, width) registry of every field the shipped views declare, plus the
named mutable ARENAS. This is the bridge's half of the field-backed seam: the shipped views are the
human-readable declaration; this file is the same map machine-readable for the workbench (the serializer
pre2/bridge/state_fields.py, named snapshot diffs, the flip proof scripts/verify_field_flip.py).

Aliases are legitimate: the views' two-names-for-two-widths convention means some bytes are covered by
two names (e.g. a word and its high byte). Values extracted from one image are always mutually consistent,
so apply order never matters for a round-trip.
"""
'''


def harvest():
    """Flatten every named field: yields (name, offset, width), absolute DGROUP offsets."""
    import pre2.views.dgroup_view as dv

    def field_descs(cls):
        seen = set()
        for klass in cls.__mro__:
            for name, d in vars(klass).items():
                if name in seen:
                    continue
                if isinstance(d, (dv._U8, dv._S8)):
                    seen.add(name); yield name, d.off, 1
                elif isinstance(d, (dv._U16, dv._S16)):
                    seen.add(name); yield name, d.off, 2

    rows = []
    for cls_name in sorted(dir(dv)):
        cls = getattr(dv, cls_name)
        if not (isinstance(cls, type) and issubclass(cls, dv.StructView)):
            continue
        base = None
        if issubclass(cls, dv.DgroupView) and cls is not dv.DgroupView:
            base = 0
        if cls is dv.PlayerView:
            base = dv.PLAYER_BASE
        if base is None:
            continue                                    # bare record classes are covered via the arrays
        for fname, off, width in sorted(field_descs(cls), key=lambda t: t[1]):
            rows.append((f"{cls_name}.{fname}", (base + off) & 0xFFFF, width))
        for aname, d in sorted(vars(cls).items()):
            if isinstance(d, dv.StructArray):
                for i in range(d.length):
                    ebase = base + d.off + i * d.stride
                    for fname, off, width in sorted(field_descs(d.struct_cls), key=lambda t: t[1]):
                        rows.append((f"{cls_name}.{aname}[{i}].{fname}", (ebase + off) & 0xFFFF, width))
    arenas = dict(getattr(dv, "ARENAS", {}))
    return rows, arenas


def render(rows, arenas) -> str:
    lines = [HEADER, "", "#: name -> (DGROUP offset, width in bytes)", "FIELDS = {"]
    for name, off, width in rows:
        lines.append(f"    {name!r}: (0x{off:04X}, {width}),")
    lines += ["}", "", "#: named mutable arenas (variable-stride record regions kept as owned byte ranges)",
              "ARENAS = {"]
    for label, (lo, hi) in arenas.items():
        lines.append(f"    {label!r}: (0x{lo:04X}, 0x{hi:04X}),")
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    rows, arenas = harvest()
    text = render(rows, arenas)
    OUT.write_text(text, encoding="utf-8", newline="")
    n_bytes = len({(o + k) & 0xFFFF for _, o, w in rows for k in range(w)})
    print(f"wrote {OUT}: {len(rows)} fields ({n_bytes:,} named bytes), {len(arenas)} arena(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
