"""Generate pre2/native/asset_tables.py — the boot-constant gameplay tables as NATIVE immutable assets.

P5 slice 1a (docs/pre2/native_dataclass_lift.md). These 9 tables are static content the game looks up every
frame (trig, sprite metrics, score values, anim-frame descriptors, ...). Today they are read out of the
historical DGROUP image by offset — ``rb(0x6F90 + angle)``. They are content, not memory: nothing writes them,
so they can simply BE native arrays, and then ``Tables`` stops speaking DOS offsets for them.

    python scripts/gen_asset_tables.py          # rewrite the generated module
    python scripts/gen_asset_tables.py --check  # verify it is current (used by the test)

This is a DEV/BRIDGE-side generator: the OUTPUT ships and carries no offset dependency, exactly like
pre2/native/boot_data.py (generated by pre2/probes/extract_boot_data.py) and pre2/bridge/field_registry.py
(generated by scripts/gen_field_registry.py). The offsets below are the extraction recipe, used once, here.

HOW THE EXTENTS WERE ESTABLISHED (do not shortcut this — each rule caught a real error):
  1. bases are read from views/tables.py programmatically, never hand-copied (hand-copying produced wrong
     addresses for cos/sin: 0x77C6/0x7846 instead of the real 0x6F90/0x7090);
  2. extent = min(next declared base, first offset in graph_layout's proven-mutable set) — never a bare
     base-gap, because the gaps contain mutable buffers (hurt_sfx's gap runs into camera_target_scratch);
  3. cross-checked against the INDEX BOUND IN THE CODE, not observation — cos/sin are indexed by a byte
     (``xlatb`` over ``phase``) so they are exactly 256, and the measured base gap is exactly 0x100;
  4. immutability PROVEN empirically over a real cold boot + *.SQZ level load, across levels 0/1/4/5/8/9/11.
     "Populated at boot" and "not routed to the object graph" both do NOT imply constant.

WHAT RULE 4 CAUGHT: ``sprite_left_hw`` (0x752A) looks like a boot constant and is NOT — the loader rewrites it.
The region is INTERLEAVED: the even byte (id<<1) is the constant half-width (0 of 461 ever change), the odd
byte (id<<1 + 1) is loader-written (460 of 460 change). So it is deliberately NOT emitted here; it belongs to
slice 1b with the rest of the per-level loaded content. ``sprite_geom`` is word-strided too but IS fully
constant — checked the same way rather than assumed.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

OUT = ROOT / "pre2" / "native" / "asset_tables.py"
DGROUP_BASE = 0x1A0F << 4

#: (native name, views.tables base attr, extent). Extents established by the 4 rules in the module docstring.
#: sprite_left_hw is EXCLUDED on purpose — see the docstring (loader-mutated, interleaved).
TABLES = [
    ("SONG_INDEX",    "SONG_INDEX",         106),   # level -> per-level song index
    ("COS",           "COS",                256),   # angle byte -> signed cos (xlatb => exactly 256)
    ("SIN",           "SIN",                256),   # angle byte -> signed sin (xlatb => exactly 256)
    ("SPRITE_GEOM",   "SPRITE_GEOM",        922),   # (id&0x1FFF)<<1 -> width byte; +1 -> height byte
    ("SPEED_CURVE",   "SPEED_CURVE",        594),   # distance-from-target -> vertical scroll speed
    ("SCORE_TABLE",   "SCORE_TABLE",         34),   # collectible id -> score value (word-indexed)
    ("SCORE_SPR_LUT", "SCORE_SPR_LUT",      112),   # collectible index -> score-spawn-effect lut byte
    ("HURT_SFX",      "HURT_SFX_TABLE",      18),   # hit count -> escalating hurt-effect id (word-indexed)
    ("ANIM_FRAME",    "ANIM_FRAME_TABLE",  2344),   # per-entity anim-frame descriptors (section-marked scan)
]

HEADER = '''"""Boot-constant gameplay tables as NATIVE immutable assets — GENERATED by scripts/gen_asset_tables.py.

**Do not edit by hand; do not add an offset here.** This module is the P5 slice-1a answer to "why does the
release still need the DOS memory image?" for the static lookup tables: it does not. These are *content* —
trig, sprite metrics, score values, anim-frame descriptors — that nothing ever writes, so they are plain
Python bytes indexed from 0, and :class:`pre2.views.tables.Tables` reads them directly instead of doing
``rb(0x6F90 + angle)`` into the historical image.

Each table is byte-identical to the span the original DOS build held, and
``tests/test_asset_tables.py`` pins that equivalence against the boot image so the two provably cannot drift.
Proven constant across a real cold boot + *.SQZ level load on levels 0/1/4/5/8/9/11 — not assumed from
"populated at boot", a heuristic that is WRONG (it would have frozen the loader-mutated ``sprite_left_hw``).

Emitted with the recipe + evidence in the generator's docstring. Regenerate against a different game build with
``python scripts/gen_asset_tables.py``.
"""
'''


def _spans():
    import pre2.views.tables as T
    return [(name, getattr(T, attr), ln) for name, attr, ln in TABLES]


def render() -> str:
    from pre2.native.boot_data import build_boot_memory
    mem = build_boot_memory()
    out = [HEADER, "from __future__ import annotations\n"]
    for name, base, ln in _spans():
        blob = bytes(mem[DGROUP_BASE + base:DGROUP_BASE + base + ln])
        assert len(blob) == ln, f"{name}: short read"
        out.append(f"\n#: {ln} bytes (the DOS build held this at DGROUP 0x{base:04X}; that offset is the\n"
                   f"#: extraction recipe only — nothing here indexes by it).\n"
                   f"{name} = bytes.fromhex(\n")
        h = blob.hex()
        for i in range(0, len(h), 96):
            out.append(f'    "{h[i:i + 96]}"\n')
        out.append(")\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="verify the generated module is current")
    args = ap.parse_args()
    text = render()
    if args.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print(f"STALE: {OUT} differs from a fresh generation — run: python scripts/gen_asset_tables.py")
            return 1
        print(f"OK: {OUT.name} is current ({len(TABLES)} tables)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    total = sum(ln for _, _, ln in TABLES)
    print(f"wrote {OUT} — {len(TABLES)} boot-constant tables, {total} bytes of native asset content")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
