"""Generate pre2/native/boot_data.py — the boot CONSTANTS the VM-less runtime starts from.

Extracts from the boot image (itself built once from PRE2.EXE by build_boot_image below) exactly the
data the native runtime reads (proven by pre2/probes/map_boot_reads.py):

  * the 64 KB DGROUP initial image (the program's initialized data segment, incl. the boot-loaded
    KEYB/ALLFONTS font band at its top — everything DS-relative reads),
  * four tiny CS-embedded table windows (the only code-segment bytes any recovered function reads),
  * zeros everywhere else (the read map proves no other pristine byte is ever read, and every
    pristine-read byte outside DGROUP/CS is zero in the image).

The generated module contains NO original executable code — just the data constants. After this,
PRE2.EXE and the VM are needed ONLY to re-run this extractor (e.g. onto a different game build).

    python -m pre2.probes.extract_boot_data [--from-exe PATH]
"""
from __future__ import annotations

import base64
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "scripts"))

DS_BASE = 0x1A0F << 4
CS_BASE = 0x1030 << 4
_BOOT_CAPTURE = (0x1030, 0x240A)     # OLDIES entry — after main()'s boot init (fonts/joystick/year/palette)

# The CS-embedded table windows the recovered code reads (map_boot_reads dynamic hits + the static audit),
# with generous padding. Everything else in the code segment is executable code we do NOT ship.
CS_WINDOWS = (
    (0x0000, 0x0010),   # cs:[0]=global pixel-shift, cs:[1]=draw mode, cs:[3]=music flag, cs:[5]=rotate count
    (0x1D60, 0x1D70),   # cs:[1D6B]=timer-ISR mod-4 phase, cs:[1D6C/1D6D]=digital-device-present flags
    (0x6770, 0x6774),   # cs:[6771]=camera-scroll done flag (5643 clears per frame; initial value)
    (0x6AA0, 0x6AD0),   # the second-pass/camera dispatch tables (cs:[6AAB..6ABC] hits + cs:[6AC3])
)


def build_boot_image_bytes(exe_path: str, game_root: str) -> bytes:
    """[WORKBENCH — the VM's only remaining use] Run the EXE to the OLDIES entry and return its memory."""
    from pre2.runtime import create_pre2_runtime
    rt = create_pre2_runtime(exe_path, game_root=game_root, native_replacements=False)
    cpu = rt.cpu
    cpu.trace_enabled = False
    for _ in range(40_000_000):
        if (cpu.s.cs & 0xFFFF, cpu.s.ip & 0xFFFF) == _BOOT_CAPTURE:
            break
        cpu.step()
    else:
        raise RuntimeError("never reached the OLDIES entry 1030:240A while extracting")
    return bytes(cpu.mem.data)


def main() -> int:
    if "--from-exe" in sys.argv:
        exe = sys.argv[sys.argv.index("--from-exe") + 1]
        print(f"running the VM over {exe} to the OLDIES entry ...")
        raw = build_boot_image_bytes(exe, str(ROOT / "assets"))
    else:
        img = ROOT / "artifacts" / "pre2_boot_image.zz"
        raw = zlib.decompress(img.read_bytes())
        print(f"extracting from {img.name}")

    dgroup = raw[DS_BASE:DS_BASE + 0x10000]
    dz = base64.b85encode(zlib.compress(dgroup, 9)).decode()
    cs_parts = []
    for lo, hi in CS_WINDOWS:
        blob = raw[CS_BASE + lo:CS_BASE + hi]
        cs_parts.append(f"    0x{lo:04X}: {blob!r},")
    cs_body = "\n".join(cs_parts)

    dz_lines = "\n".join(f'    "{dz[i:i + 96]}"' for i in range(0, len(dz), 96))
    out = f'''"""Boot constants for the VM-less native runtime — GENERATED by pre2/probes/extract_boot_data.py.

The initial machine state the native game starts from: the 64 KB DGROUP (the program's initialized data
segment, incl. the boot-loaded font band) + the four CS-embedded table windows the recovered code reads.
Everything else boots as zeros (pre2/probes/map_boot_reads.py proves nothing else is ever read).
Contains NO original executable code. Regenerate against a different game build with the extractor.
"""
import base64
import zlib

DS_BASE = 0x1A0F << 4      # DGROUP paragraph (the GOG build's data segment)
CS_BASE = 0x1030 << 4      # code segment base (only the table windows below are populated)
IMAGE_LEN = 0x140000       # 1 MB address space + the 4 x 64 KB EGA plane shadow

_DGROUP_Z = (
{dz_lines}
)

CS_TABLES = {{
{cs_body}
}}


def build_boot_memory() -> bytearray:
    """The initial native memory image: zeros + DGROUP + the CS table windows."""
    data = bytearray(IMAGE_LEN)
    data[DS_BASE:DS_BASE + 0x10000] = zlib.decompress(base64.b85decode("".join(_DGROUP_Z)))
    for off, blob in CS_TABLES.items():
        data[CS_BASE + off:CS_BASE + off + len(blob)] = blob
    return data
'''
    dst = ROOT / "pre2" / "native" / "boot_data.py"
    dst.write_text(out, encoding="utf-8")
    print(f"wrote {dst} ({len(out):,} chars; DGROUP compressed {len(dz):,} b85 chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
